<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup> 
        <PackageId>Cendryon.AspNetCore</PackageId>
        <Version>1.0.0</Version>
        <Authors>Cendryon s.r.o.</Authors>
        <Company>Cendryon s.r.o.</Company>

        <!-- Descriptive metadata -->
        <Title>Cendryon.AspNetCore</Title>
        <Description>
            ASP.NET Core utilities providing unified result mapping, correlation ID propagation,
            version headers, and automatic RFC 7807 ProblemDetails responses for Cendryon.Results.
            Includes middleware, filters, and IActionResult extensions for controllers and minimal APIs.
        </Description>
        <PackageTags>Cendryon;results;error;problem-details;cqrs;clean-architecture;asp-net;asp-net-core</PackageTags>
        <RepositoryUrl>https://github.com/cendryon-technology/cendryon-core-packages</RepositoryUrl>
        <PackageProjectUrl>https://github.com/cendryon-technology/cendryon-core-packages</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageIcon>icon.png</PackageIcon>
        <RepositoryType>git</RepositoryType>

        <!-- Optional packaging controls -->
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IncludeSymbols>false</IncludeSymbols>
        <IncludeSource>false</IncludeSource>
    </PropertyGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Cendryon.Results\Cendryon.Results.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../README.md" Pack="true" PackagePath="" />
        <None Include="../../LICENSE" Pack="true" PackagePath="" />
        <None Include="../../icon.png" Pack="true" PackagePath="" />
    </ItemGroup>
</Project>
